defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simsiam-synth-linear"
pretrained_feature_extractor: "/projects/imagenet_synthetic/model_checkpoints/solo-learn/solo_trained_models/simsiam/8bfvfkvb/simsiam-all-synthetic-imagenet-8bfvfkvb-ep=99.ckpt"
backbone:
  name: "resnet50"
pretrain_method: "simsiam"
data:
  dataset: imagenet
  train_path: "/datasets/imagenet/train"
  val_path: "/datasets/imagenet/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 1024
  lr: 30.0
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "/projects/imagenet_synthetic/model_checkpoints/solo-learn/solo_trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
