defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "swav-imagenet-linear-eval"
pretrained_feature_extractor: "/projects/imagenet_synthetic/model_checkpoints/solo-learn/solo_trained_models/swav/4h806hg4/swav-imagenet-4h806hg4-ep=99.ckpt"
method: "swav"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  queue_size: 3840
  proj_output_dim: 128
  num_prototypes: 3000
  epoch_queue_starts: 50
  freeze_prototypes_epochs: 2
  temperature: 0.1
data:
  dataset: imagenet
  train_path: "/datasets/imagenet/train"
  val_path: "/datasets/imagenet/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 1024
  lr: 0.15
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "/projects/imagenet_synthetic/model_checkpoints/solo-learn/solo_trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
