defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simsiam-synth-imagenet-linear"
pretrained_feature_extractor: "trained_models/simsiam/7hze8zdp/simsiam-synth-imagenet-7hze8zdp-ep=99.ckpt"
method: "simsiam"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 4096
  pred_hidden_dim: 512
  temperature: 0.2
data:
  dataset: imagenet
  train_path: "/scratch/ssd004/datasets/imagenet256/train"
  val_path: "/scratch/ssd004/datasets/imagenet256/val"
  # format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 1024
  lr: 0.1
  weight_decay: 0
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 0
  scheduler_interval: "epoch"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
  max_hours: 100
# overwrite PL stuff
max_epochs: 100
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed