defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "moco-inaturalist-diff-linear"
pretrained_feature_extractor: "/projects/imagenet_synthetic/model_checkpoints/solo-learn/solo_trained_models/mocov2plus/4436ayvn/mocov2plus-imagenet-synthetic-4436ayvn-ep=94.ckpt"
backbone:
  name: "resnet50"
pretrain_method: "mocov2plus"
data:
  dataset: inaturalist
  train_path: "/datasets/inat_comp/2018/"
  val_path: "/datasets/inat_comp/2018/"
  format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 512
  lr: 0.1
  weight_decay: 0
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 0
  scheduler_interval: "epoch"
checkpoint:
  enabled: True
  dir: "/projects/imagenet_synthetic/model_checkpoints/solo-learn/solo_trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
