defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: "/projects/imagenet_synthetic/model_checkpoints/solo-learn/solo_trained_models/simclr/2fnyx7sf/paper-simclr-imagenet-2fnyx7sf-ep=99.ckpt"

name: "simclr-food101-linear"
pretrained_feature_extractor: None
backbone:
  name: "resnet50"
pretrain_method: "simclr"
data:
  dataset: food101
  train_path: "/projects/imagenet_synthetic/fereshteh_datasets"
  val_path: "/projects/imagenet_synthetic/fereshteh_datasets"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 1.0
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
